name: Actualizacion Lunes 9am

on:
  schedule:
    # Se ejecuta todos los lunes a las 15:00 UTC (9:00 AM hora CDMX)
    - cron: '0 15 * * 1'
  workflow_dispatch: # Boton para ejecutarlo manualmente cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Descargar el codigo del repositorio
        uses: actions/checkout@v3

      - name: 2. Configurar Python en la nube
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 3. Instalar y actualizar librerias (Fix Yahoo Error)
        run: |
          pip install --upgrade yfinance pandas

      - name: 4. Ejecutar el Robot Recolector (harvester.py)
        run: python harvester.py

      - name: 5. Guardar los cambios en el repositorio
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add logit_data.csv
          git commit -m "Actualizacion automatica: Datos Logit del Lunes" || echo "No hay cambios"
          git push
